name: publish

on:
  workflow_dispatch:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: quarto-dev/quarto-actions/setup@v2
    - run:
        quarto render
    - uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

  deploy:
    needs: build
    # Set permissions to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/configure-pages@v4
    - uses: actions/deploy-pages@v4
